### PR TITLE
Allow to use symfony framework's client

### PR DESCRIPTION
**Pull request by sroze**
The Symfony framework's `Client` class don't have the `setHeader` method, but they can be passed while calling `request` as introduced by 06c075acc738b10984d970dc3a218df9113e1860.

This remove the fatal error of undefined method `getClient`.

### CODE REVIEW

**Comment by sroze** [comment]
ping @sanpii

**Comment by sanpii** [comment]
See https://github.com/Behatch/contexts/issues/119#issuecomment-94964913
